apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
        - name: demo1
          image: hamgeonwook/demo1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: demo1-service
spec:
  ports:
    - port: 9002
      targetPort: 8080
      protocol: TCP
  selector:
    app: demo1