apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: surveyanswer
          image: hamgeonwook/surveyanswer:latest
          ports:
            - containerPort: 8080
        - name: surveydocument
          image: hamgeonwook:surveydocument:latest
          ports:
            - containerPort: 8080
        - name: surveyanalyze
          image: hamgeonwook:surveyanalyze:latest
          ports:
            - containerPort: 8080
        # Add more containers for other modules if needed
