apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo1
          image: hamgeonwook/demo1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
        - name: demo2
          image: hamgeonwook/demo2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080