apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myweb-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: docker.io/mysql
          imagePullPolicy: Always  #Do not use remote mirror
          name: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - name: mysql-svc
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP