apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: surveyanswer-service
spec:
  selector:
    app: surveyanswer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: surveydocument-service
spec:
  selector:
    app: surveydocument
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: surveyanalyze-service
spec:
  selector:
    app: surveyanalyze
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
