apiVersion: v1
kind: Service
metadata:
  name: demo1-service
spec:
  selector:
    app: demo1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: demo2-service
spec:
  selector:
    app: demo2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
