apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveyanswer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: surveyanswer
  template:
    metadata:
      labels:
        app: surveyanswer
    spec:
      containers:
        - name: surveyanswer
          image: hamgeonwook/surveyanswer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: surveyanswer-service
spec:
  ports:
    - port: 8083
      targetPort: 8080
      protocol: TCP
  selector:
    app: surveyanswer