apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveydocument
spec:
  replicas: 2
  selector:
    matchLabels:
      app: surveydocument
  template:
    metadata:
      labels:
        app: surveydocument
    spec:
      containers:
        - name: surveydocument
          image: hamgeonwook/surveydocument:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: surveydocument-service
spec:
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
  selector:
    app: surveydocument